const products = [
  {
    title: 'Funny Many',
    description: 'Smart text here',
    price: 99,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Merry Poppins',
    description: 'Lady that can fly',
    price: 59,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Monte Christo',
    description: 'Rich duke after jail',
    price: 199,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Winnie the Pooh',
    description: 'Puha puha puha!',
    price: 10,
    countInStock: 1,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Star Wars',
    description: 'Smart text here',
    price: 99,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Luck Skywalker',
    description: 'Smart text here',
    price: 99,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Mark Hamill',
    description: 'Smart text here',
    price: 59,
    countInStock: 8,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Old Ben Kenobi',
    description: 'Smart text here',
    price: 89,
    countInStock: 14,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Far Far Away',
    description: 'Smart text here',
    price: 699,
    countInStock: 10,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'High Ground',
    description: 'Smart text here',
    price: 299,
    countInStock: 7,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Stay on Target',
    description: 'Smart text here',
    price: 22,
    countInStock: 1,
    isFeatured: true,
    isArchived: false,
  },
  {
    title: 'Fly Casual',
    description: 'Smart text here',
    price: 9,
    countInStock: 13,
    isFeatured: true,
    isArchived: true,
  },
]

module.exports = { products }
